In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Get value at index 8
arr[8]

8

In [7]:
#value in range
arr[1:5]

array([1, 2, 3, 4])

In [8]:
#value upto index 7
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
#value from a certain index
arr[7:]

array([ 7,  8,  9, 10])

INDEXING 2D ARRAY

arr[row][col]


In [11]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
#return row
arr_2d[2]

array([35, 40, 45])

In [14]:
#get element 30
arr_2d[1][2] #also arr_2d[1,2]

30

In [15]:
arr_2d[2][1] #also arr_2d[2,1]

40

In [16]:
#range
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [22]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [26]:
arr_2d[0:2, :2]

array([[ 5, 10],
       [20, 25]])

In [27]:
arr_2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

CONDITIONAL SELECTION

In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
bool_arr = arr > 5

In [32]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr<3]

array([1, 2])