Vectors (1-D array), Metrices (2-D array)

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
metrices = [[1,2,3],[5,4,6],[9,5,7]]
np.array(metrices)

array([[1, 2, 3],
       [5, 4, 6],
       [9, 5, 7]])

arange - prints vector sequentially.
It can take 2 parameters (start, stop) or 3 parameters where
the third parameter is step (start, stop, step)

In [4]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [5]:
#print array of even numbers between 0 - 10
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0.5,1,20)

array([0.5       , 0.52631579, 0.55263158, 0.57894737, 0.60526316,
       0.63157895, 0.65789474, 0.68421053, 0.71052632, 0.73684211,
       0.76315789, 0.78947368, 0.81578947, 0.84210526, 0.86842105,
       0.89473684, 0.92105263, 0.94736842, 0.97368421, 1.        ])

In [14]:
#identity matrix, is a 2d square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#RANDOM

In [16]:
np.random.rand(5)

array([0.51923489, 0.03560714, 0.88012822, 0.73655935, 0.76745974])

In [17]:
np.random.rand(5,5)

array([[0.69649126, 0.60668814, 0.16405134, 0.33962669, 0.12993048],
       [0.19373114, 0.90019922, 0.00830313, 0.93706794, 0.12298526],
       [0.29576799, 0.05601134, 0.55028899, 0.55571622, 0.85400055],
       [0.03142557, 0.65706878, 0.55682321, 0.55644146, 0.86140907],
       [0.08379319, 0.45700831, 0.15620214, 0.8402231 , 0.94893089]])

In [19]:
np.random.randn(2)

array([0.6609694 , 0.84712733])

In [20]:
np.random.randn(4,4)

array([[ 0.07766005, -0.77073087, -0.01708281,  1.22465172],
       [-1.05847762,  1.08557306,  1.41402864, -0.4353166 ],
       [ 0.72225849,  1.63670672,  1.32067953, -0.62737404],
       [ 0.07028481, -0.75968558, -0.17757767, -0.35216748]])

In [22]:
np.random.randint(1, 50, 10)

array([11, 42, 12, 41,  6, 24, 47,  8, 31,  5])

ATTRIBUTES

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
radarr = np.random.randint(0,50,10)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
radarr.max()

49

In [34]:
radarr.argmax()

0

In [35]:
radarr.argmin()

7

In [36]:
radarr.dtype

dtype('int32')