In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr_2 = np.arange(10, 21)

In [4]:
#addition
arr + arr_2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
arr_2 - arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [6]:
arr * arr_2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [7]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [8]:
np.sqrt(arr_2)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [9]:
np.abs(arr_2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
np.exp(arr_2)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [13]:
excercise = np.random.randint(1, 52, 50).reshape(5,10)
excercise

array([[31,  1, 15, 24, 47, 22, 10, 41, 17, 29],
       [24, 35,  6, 27, 42, 25, 31, 36, 50, 28],
       [ 3,  3, 32, 30, 50, 22, 14, 40, 34, 42],
       [46, 48,  3,  6, 17,  5, 10, 45,  9, 26],
       [17, 37, 35,  4, 26,  6,  4, 51, 36, 47]])

In [15]:
excercise[1:3, 4:6]

array([[42, 25],
       [50, 22]])

In [16]:
excercise[3:,4:8]

array([[17,  5, 10, 45],
       [26,  6,  4, 51]])

In [19]:
excercise[1:4, 1:6]

array([[35,  6, 27, 42, 25],
       [ 3, 32, 30, 50, 22],
       [48,  3,  6, 17,  5]])